### ISSUE TITLE
try different lambdas

### ISSUE THREAD

**Issue by gideonite** [ratschlab/projects2019-boosting-bbvi-pyro#5]

**Comment by gideonite** [comment]
if it's not a lot of work, let's just stop hard coding lambda.

**Comment by lorenzkuhn** [comment]
Here are some preliminary results for different lambdas. The context is still our bimodal posterior toy problem with true modes around -2 and 2. I've used the same initialisation and hyperparameters that gave us the best approximation for two approximation components. 

As we'd expect, larger values for lambda lead to larger variances for the approximation components. The difference the change of lambda makes for the variance is quite small however. So small actually that it's easier to visualise the differences in a table rather than a plot of the approximation: 

| lambda | variance_1 | variance_2 |
|--------|------------|------------|
| 0      | 0.3676     | 0.1255     |
| 0.2    | 0.3717     | 0.1291     |
| 0.4    | 0.3757     | 0.1328     |
| 0.6    | 0.3799     | 0.1364     |
| 0.8    | 0.3841     | 0.1401     |
| 1      | 0.3883     | 0.1438     |

where `variance_1` is the variance of the first approximation component and `variance_2` the variance of the second approximation component.

For completeness sake, here are the plots of the resulting approximations:
![lambda=0](https://user-images.githubusercontent.com/9898136/69006330-f19d0800-092d-11ea-9f18-4fafe9b29bb5.png)
![lambda=0 2](https://user-images.githubusercontent.com/9898136/69006326-f1047180-092d-11ea-9f45-4b7cd239bc35.png)
![lambda=0 4](https://user-images.githubusercontent.com/9898136/69006327-f1047180-092d-11ea-9a1e-db6950481e25.png)
![lambda=0 6](https://user-images.githubusercontent.com/9898136/69006328-f19d0800-092d-11ea-839d-9d346effb177.png)
![lambda=0 8](https://user-images.githubusercontent.com/9898136/69006329-f19d0800-092d-11ea-80d1-440878b704fe.png)

![lambda=1](https://user-images.githubusercontent.com/9898136/69006331-f19d0800-092d-11ea-8862-5269f58ba985.png)

I guess given the plots in https://github.com/ratschlab/projects2019-boosting-bbvi-pyro/issues/9, also suggest that changing lambda would have a small effect.
